[2025-04-25T06:51:54.126+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.read_Data manual__2025-04-25T06:51:51.003264+00:00 [queued]>
[2025-04-25T06:51:54.134+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.read_Data manual__2025-04-25T06:51:51.003264+00:00 [queued]>
[2025-04-25T06:51:54.134+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-25T06:51:54.145+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): read_Data> on 2025-04-25 06:51:51.003264+00:00
[2025-04-25T06:51:54.152+0000] {standard_task_runner.py:60} INFO - Started process 87 to run task
[2025-04-25T06:51:54.155+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'read_Data', 'manual__2025-04-25T06:51:51.003264+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpfb2no6z9']
[2025-04-25T06:51:54.158+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask read_Data
[2025-04-25T06:51:54.207+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.read_Data manual__2025-04-25T06:51:51.003264+00:00 [running]> on host 8f416ae2c250
[2025-04-25T06:51:54.276+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='read_Data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T06:51:51.003264+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-25T06:51:51.003264+00:00'
[2025-04-25T06:51:54.285+0000] {spark_submit.py:304} INFO - Could not load connection string my_spark_conn, defaulting to yarn
[2025-04-25T06:51:54.286+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --verbose ./include/scripts/read.py
[2025-04-25T06:51:55.322+0000] {spark_submit.py:634} INFO - Using properties file: null
[2025-04-25T06:51:55.421+0000] {spark_submit.py:634} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-04-25T06:51:55.421+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-04-25T06:51:55.422+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-04-25T06:51:55.422+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-04-25T06:51:55.423+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-04-25T06:51:55.423+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-04-25T06:51:55.423+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-04-25T06:51:55.424+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-04-25T06:51:55.424+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-04-25T06:51:55.424+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-04-25T06:51:55.425+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-04-25T06:51:55.456+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose ./include/scripts/read.py. Error code is: 1.
[2025-04-25T06:51:55.460+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=my_dag, task_id=read_Data, execution_date=20250425T065151, start_date=20250425T065154, end_date=20250425T065155
[2025-04-25T06:51:55.476+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task read_Data (Cannot execute: spark-submit --master yarn --name arrow-spark --verbose ./include/scripts/read.py. Error code is: 1.; 87)
[2025-04-25T06:51:55.533+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-25T06:51:55.553+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
